### ISSUE TITLE
Use own domain for device

### ISSUE THREAD

**Issue by molnarti** [syncloud/platform#236] opened 2017-02-16 20:40 UTC
Is it possible to set up syncloud with my own domain, instead of the syncloud.it one? the reason for that is that i need to access my homecloud from a location where the syncloud domain is blocked

**Comment by cyberb** [comment] 2017-02-17 07:17
Try adding two a records to your DNS:
example.com device_ip
*.example.com device_ip

example.com will show device UI.
files.example.com will show Files app.

Remember that sometimes device ip is changing and you will need to update it accordingly.

**Comment by molnarti** [comment] 2017-02-25 19:04
your solution does not solve the navigation within synclouds's interface. when clicking on an app it will still take me to files.syncloud.it while i want it to take me to 192.168.1.25/files.html (or whathever is files.syncloud.it redirected to)

**Comment by cyberb** [comment] 2017-02-28 07:03
Right, try changing domain in /opt/data/platform/user_platform.cfg

**Comment by cyberb** [comment] 2017-10-02 07:33
Duplicate of https://github.com/syncloud/platform/issues/264

**Closed by cyberb** 2017-10-02 07:33 UTC
Labels: feature
