### ISSUE TITLE
ownCloud desktop client: Connection is closed when uploading large files (> 2GB)

### ISSUE THREAD

**Issue by jpma89** [syncloud/platform#103] opened 2016-01-13 21:32 UTC
Platform: v366
ownCloud: v76

Issue occurs independent from filesystem (ext4, NTFS) and disk type (2,5" w/o external power, 3,5" w/ external power).

All ownCloud related config settings are default.

Tested using official ownCloud client 2.1.0 running on Win8.1

**Comment by cyberb** [comment] 2016-01-13 23:53
This is actually php/arm 32 bit limitation, I do not think arm 64 CBSs are popular yet.
Had to split 4 gig file just 2 minutes ago myself to share it with my friend :)

Let me know if you find anything on the internet though!

**Comment by jpma89** [comment] 2016-01-15 20:51
If I remember correctly, syncing files larger than 2GB was working fine fir me with Syncloud v0.8. Is that possible somehow?

**Comment by cyberb** [comment] 2016-01-15 23:24
You know after googling it a bit I think you may be right and as ownCloud sync uploads files in chunks this may be fine.

Could you try one more time and check logs for any specific error message in /opt/data/owncloud/*.log

**Comment by cyberb** [comment] 2016-01-15 23:38
I did one more test by generating 10g file and tried to see it on ownCloud webui. It did not show up and I got this on the owncloud.log:

{"reqId":"mymbU8Si96iW736ZLhMX","remoteAddr":"127.0.0.1","app":"PHP","message":"fopen(\/data\/owncloud\/test\/files\/big.file): failed to open stream: Value too large for defined data type at \/opt\/app\/owncloud\/owncloud\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2016-01-13T23:31:26+00:00"}

**Comment by jpma89** [comment] 2016-01-16 11:50
For me it did show up again today. Error message in owncloud.log is:

{"reqId":"V51jx0ziXVTjA3+WLzK4","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"Documents\\\/syncloud-beagleboneblack-1.0.img-chunking-2822733817-420-419\\\" is locked\",\"Exception\":\"OC\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('syncloud-beagle...', Resource id #315)\\n#1 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('Documents\\\/syncl...', Resource id #315, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/remote.php(137): require_once('\\\/opt\\\/app\\\/ownclo...')\\n#8 {main}\",\"File\":\"\\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":121}","level":4,"time":"2016-01-16T11:45:33+00:00"}
{"reqId":"ggESbh8DZXNrEQ2LyJQU","remoteAddr":"127.0.0.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"Documents\\\/syncloud-beagleboneblack-1.0.img-chunking-2822733817-420-419\\\" is locked\",\"Exception\":\"OC\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('syncloud-beagle...', Resource id #315)\\n#1 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('Documents\\\/syncl...', Resource id #315, NULL)\\n#2 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#3 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#4 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#5 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#7 \\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/remote.php(137): require_once('\\\/opt\\\/app\\\/ownclo...')\\n#8 {main}\",\"File\":\"\\\/opt\\\/app\\\/owncloud\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php\",\"Line\":121}","level":4,"time":"2016-01-16T11:48:38+00:00"}

**Comment by cyberb** [comment] 2016-01-16 17:15
Looks like this is a different issue related to locks.
https://github.com/owncloud/core/issues/20380

They said it was fixed in 8.2.2.

Could you try their workaround by cleaning oc_file_locks mysql table?

**Comment by cyberb** [comment] 2016-01-16 17:47
By the way I have just uploaded ownCloud v78 with php fix for large files. Tested on 10g file download.

**Comment by jpma89** [comment] 2016-01-26 19:56
Issue reoccured when downloading big image files (> 2 GB).
No entries to  /opt/data/owncloud/*.log only in ownCloud desktop client.

**Comment by cyberb** [comment] 2016-01-28 09:16
Could you try downloading from web the same file?

**Comment by jpma89** [comment] 2016-01-28 20:21
Same issue when downloading the file from the web interface. The download just stopps after a random number of megabytes. Nothing is being logged to /opt/data/owncloud/*

**Comment by cyberb** [comment] 2016-01-30 13:20
Did more testing and actually have the same problem, files stop downloading right after 1gb, could you check /opt/data/platform/log/nginx_error.log

**Comment by jpma89** [comment] 2016-01-30 15:05
2016/01/30 13:31:37 [warn] 532#0: *28 an upstream response is buffered to a temporary file /opt/app/platform/nginx/proxy_temp/1/00/0000000001 while reading upstream, client: 192.168.0.2, server: owncloud.*, request: "GET /core/vendor/jquery/jquery.min.js?v=fe4051aaefe5f5f41838b036bc42d34e HTTP/1.1", upstream: "http://127.0.0.1:1082/core/vendor/jquery/jquery.min.js?v=fe4051aaefe5f5f41838b036bc42d34e", host: "owncloud.<syncloud devicename>.syncloud.it"

...


2016/01/30 13:33:41 [error] 532#0: *35 upstream prematurely closed connection while reading upstream, client: 192.168.0.2, server: owncloud.*, request: "GET /index.php/apps/files/ajax/download.php?dir=%2FB%2FBeaglebone%20Black&files=BBB-eMMC-flasher-debian-7.4-2014-02-16-2gb.img&downloadStartSecret=4s5316dynqr27qfr HTTP/1.1", upstream: "http://127.0.0.1:1082/index.php/apps/files/ajax/download.php?dir=%2FB%2FBeaglebone%20Black&files=BBB-eMMC-flasher-debian-7.4-2014-02-16-2gb.img&downloadStartSecret=4s5316dynqr27qfr", host: "owncloud.<syncloud devicename>.syncloud.it"

**Comment by cyberb** [comment] 2016-02-06 10:58
I was able to reproduce timeout inside our test harness, it happens constantly on big files >2g.

Increasing timeouts on both platform nginx (front) and on ownCloud nginx to 300 seconds fixed the problem.

Platform: https://github.com/syncloud/platform/commit/89ee56bda99e96bbc6bb54b6511ff71f1b1a8dff

ownCloud: https://github.com/syncloud/owncloud/commit/fea18b3c05f2e3f47f8f19acfb0508aaea20c91d

It is available on master channel, the upcoming release will bring it stable channel.

**Closed** 2016-02-06 11:39 UTC
Labels: bug
