### ISSUE TITLE
OpenVPN service

### ISSUE THREAD

**Issue by dani-77** [syncloud/platform#387] opened 2019-04-12 13:01 UTC
It would be great to have openVPN as app; it would open our server securely outside our Wi-Fi, even being in internal mode.

**Comment by cyberb** [comment] 2019-04-12 17:02
Duplicate of this: https://github.com/syncloud/platform/issues/298

**Closed by cyberb** 2019-04-12 17:02 UTC

**Comment by dani-77** [comment] 2019-04-12 17:15
Ok. Didn’t saw it.
